# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

r:
  - oldrel
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
